import React from "react"
import Head from "next/head"
import Link from "next/link"

const Layout = ({ children, title }) => {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="bg-cyan-900 py-10 mb-10">
        <Link href="/">
          <h1 className="text-6xl text-center text-green-400">{title}</h1>
        </Link>
      </header>

      <main className="container mx-auto">{children}</main>

      <footer className="flex justify-center items-center mt-10 bg-cyan-900 py-10">
        All rights reserved
      </footer>
    </div>
  )
}

export default Layout
