import Head from "next/head"

interface Props {
  title: string
}

export const HeadComponent = ({ title }: Props) => {
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}
